### ISSUE TITLE
Curator and zookeeper versions incompatibilities

### ISSUE THREAD

**Issue by MegaPapa** [bootique/bootique-curator#12]
bootique-curator has version incompatibilities between curator-recipes and zookeeper. It's throws next NoSuchMethodError exception.
<pre>
1) Error in custom provider, java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
  at io.bootique.curator.CuratorModule.createCurator(CuratorModule.java:43)
  while locating org.apache.curator.framework.CuratorFramework

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at io.bootique.job.zookeeper.lock.ZkMutex.acquire(ZkMutex.java:38)
	at io.bootique.job.zookeeper.lock.ZkClusterLockHandler.lambda$lockingJob$0(ZkClusterLockHandler.java:57)
	at io.bootique.job.runnable.ErrorHandlingRunnableJobFactory.lambda$runnable$0(ErrorHandlingRunnableJobFactory.java:45)
	at io.bootique.job.scheduler.DefaultScheduler.lambda$null$8(DefaultScheduler.java:239)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:40)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:256)
	at io.bootique.curator.CuratorModule.createCurator(CuratorModule.java:50)
	at io.bootique.curator.CuratorModule$$FastClassByGuice$$9729a7ae.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 13 more
</pre>

**Comment by MegaPapa** [comment]
Judging by stack trace, problem is hided in guava version incompatibilities. Guava is used in guice (from bootique core) and in curator. I think, simpliest way resolve this incompatibilities is to update curator version to 4.0.0.
